# === simulate.yaml ===
# Configuration pour la commande simulate
# Usage: python3 scripts/main2.py simulate --yaml config/yaml/simulate.yaml

simulate:
  pre-input: data/prot_mammals
  pre-output: results/preprocessed
  minseq: 5
  maxsites: 2000
  minsites: 100
  alphabet: aa
  align: results/preprocessed/clean_data
  tree: data/prot_mammals/trees
  config: config/bpp/aa/WAG_frequencies.bpp
  sim-output: results/simulations
  ext_rate: 0.3
  tree-output: results/trees
  metrics-output: results/metrics